#!/bin/sh
Selection=true

export BROWSER=firefox
#export GTK_THEME=Adwaita-dark
#export GTK_THEME=Tokyonight-Storm-B
export EDITOR=vim
export QT_QPA_PLATFORMTHEME=qt5ct
export LANG=zh_CN.UTF-8

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=/usr/local/share:/usr/share

export MOZ_USE_XINPUT2=1

export WINIT_WAYLAND_CSD_THEME=Dark

name=$(basename "$1")

if [ "$name" = "wayfire" ]; then
    export MOZ_ENABLE_WAYLAND=1
    export GVIM_ENABLE_WAYLAND=1
    export QT_QPA_PLATFORM="wayland;xcb"
    export SDL_VIDEODRIVER=wayland
    export XDG_CURRENT_DESKTOP=Wayfire
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
elif [ "$name" = "startxfce4" ]; then
    /usr/bin/clipmenud &
    /usr/bin/xrandr --output Virtual-1 --auto
fi

#gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface font-name "DejaVuSansM Nerd Font Mono Regular 14"
gsettings set org.gnome.desktop.interface cursor-theme "oreo_pink_cursors"
gsettings set org.gnome.desktop.interface cursor-size "32"
gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal "xfce4-terminal"
gsettings set org.gnome.gedit.preferences.editor tabs-size 4
gsettings set org.gnome.gedit.preferences.editor editor-font "DejaVuSansM Nerd Font Mono 16"
gsettings set org.gnome.gedit.preferences.editor scheme "solarized-light"
gsettings set org.gnome.desktop.interface cursor-size 32
gsettings set org.gnome.desktop.interface icon-theme Adwaita

exec dbus-launch $@ > ~/.cache/$name.log 2>&1

