#!/bin/bash

## Get data
function meta(){
    playerctl -a metadata -p musicfox,yesplaymusic,kdeconnect,firefox "$@"
}

STATUS="$(meta --format '{{status}}')"
COVER="/tmp/.music_cover.jpg"

## Get status
get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo "󰏤"
	else
		echo "󰐊"
	fi
}

## Get song
get_song() {
	song=`meta --format '{{markup_escape(title)}}'`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`meta --format '{{artist}}'`
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	# time=`mpc status | grep "%)" | awk '{print $4}' | tr -d '(%)'`
    time=50
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
    ctime=$(meta --format '{{duration(position)}}')
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
    ttime=$(meta --format '{{duration(mpris:length)}}')
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Get cover
get_cover() {
    url=$(meta --format '{{mpris:artUrl}}')
    curl $url -o ${COVER}
	STATUS=$?

	# Check if the file has a embbeded album art
	if [ "$STATUS" -eq 0 ];then
		echo "$COVER"
	else
		echo "images/music.png"
	fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl next; sleep 2; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl previous; sleep 2; get_cover; }
fi
